[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "ExtraBold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "ExtraBold Italic" }
#
# # The new one
# normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
# bold = { family = "CaskaydiaCove Nerd Font Mono", style = "ExtraBold" }
# italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
# bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "ExtraBold Italic" }
#
# normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# bold = { family = "JetBrainsMono Nerd Font", style = "ExtraBold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }
#
#
#
#
size = 20.0



[window]
padding = {x = 0, y =0}

[keyboard]
bindings = [
    { key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" },
    # { key= "L", mods= "Control", action= "ClearHistory" },

]


  # Vague for Alacritty
# Upstream: https://github.com/vague-theme/vague-alacritty/blob/main/vague.toml

[colors.primary]
background = '#141415'
foreground = '#cdcdcd'

[colors.normal]
black = '#252530'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#cdcdcd'

[colors.bright]
black = '#606079'
red = '#e08398'
green = '#99b782'
yellow = '#f5cb96'
blue = '#8ba9c1'
magenta = '#c9b1ca'
cyan = '#bebeda'
white = '#d7d7d7'

[colors.hints.start]
foreground = "CellBackground"
background = "CellForeground"

[colors.hints.end]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.matches]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.focused_match]
foreground = "CellBackground"
background = '#f3be7c'
