[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Bold" }
bold = { family = "Iosevka Nerd Font Mono", style = "ExtraBold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "ExtraBold Italic" }
#
# # The new one
# normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
# bold = { family = "CaskaydiaCove Nerd Font Mono", style = "ExtraBold" }
# italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
# bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "ExtraBold Italic" }
#
# normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# bold = { family = "JetBrainsMono Nerd Font", style = "ExtraBold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }
#
#
#
#
size = 16.0
#
#
#
[window]
padding = {x = 0, y =0}

[keyboard]
bindings = [
    { key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" }
]
#
#
[colors.primary]
foreground = "#ECE1D7"
# background = "#292222"
background = "#000000"
[colors.normal]
black      = "#34302C"
red        = "#BD8183"
green      = "#78997A"
yellow     = "#E49B5D"
blue       = "#7F91B2"
magenta    = "#B380B0"
cyan       = "#7B9695"
white      = "#C1A78E"
[colors.bright]
black      = "#867462"
red        = "#D47766"
green      = "#85B695"
yellow     = "#EBC06D"
blue       = "#A3A9CE"
magenta    = "#CF9BC2"
cyan       = "#89B3B6"
white      = "#ECE1D7"




