[window]
opacity = 0.00
padding = { x = 25, y = 15 }


[font]
size = 18.0

# Normal font face
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

# Bold font face
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# Italic font face
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Bold italic font face
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"



